language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpcs
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls -v